language: android

android:
  components:
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

jdk:
  - oraclejdk8

script: ./gradlew clean test

notifications:
  email: true

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
